DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
DROP TABLE IF EXISTS states;

CREATE TABLE IF NOT EXISTS states (
    id SERIAL PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE,
    description VARCHAR(300) NOT NULL
);

INSERT INTO states (name, description) VALUES
('Active', 'The novella is currently being written, edited, or developed. The author is actively working on it.'),
('Completed', 'The novella has been fully written and is ready for publication or submission for editing.'),
('Abandoned', 'The author has ceased work on the novella without completion. This could happen for various reasons, such as loss of interest, change of plans, or lack of time.'),
('Revision', 'The novella requires significant revision or rewriting. Changes to the plot, characters, or style may be necessary.'),
('On Hold', 'Work on the novella has been temporarily suspended for some reason, but the author plans to return to it in the future.');
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username varchar(90) NOT NULL UNIQUE,
    email varchar(90) NOT NULL UNIQUE,
    password_hash varchar(120) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_timestamp
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();DROP TABLE IF EXISTS countries;

CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    code VARCHAR(2) NOT NULL DEFAULT '',
    name VARCHAR(100) NOT NULL DEFAULT ''
);

INSERT INTO countries (id, code, name) VALUES
       (1, 'AF', 'Afghanistan'),
       (2, 'AL', 'Albania'),
       (3, 'DZ', 'Algeria'),
       (4, 'DS', 'American Samoa'),
       (5, 'AD', 'Andorra'),
       (6, 'AO', 'Angola'),
       (7, 'AI', 'Anguilla'),
       (8, 'AQ', 'Antarctica'),
       (9, 'AG', 'Antigua and Barbuda'),
       (10, 'AR', 'Argentina'),
       (11, 'AM', 'Armenia'),
       (12, 'AW', 'Aruba'),
       (13, 'AU', 'Australia'),
       (14, 'AT', 'Austria'),
       (15, 'AZ', 'Azerbaijan'),
       (16, 'BS', 'Bahamas'),
       (17, 'BH', 'Bahrain'),
       (18, 'BD', 'Bangladesh'),
       (19, 'BB', 'Barbados'),
       (20, 'BY', 'Belarus'),
       (21, 'BE', 'Belgium'),
       (22, 'BZ', 'Belize'),
       (23, 'BJ', 'Benin'),
       (24, 'BM', 'Bermuda'),
       (25, 'BT', 'Bhutan'),
       (26, 'BO', 'Bolivia'),
       (27, 'BA', 'Bosnia and Herzegovina'),
       (28, 'BW', 'Botswana'),
       (29, 'BV', 'Bouvet Island'),
       (30, 'BR', 'Brazil'),
       (31, 'IO', 'British Indian Ocean Territory'),
       (32, 'BN', 'Brunei Darussalam'),
       (33, 'BG', 'Bulgaria'),
       (34, 'BF', 'Burkina Faso'),
       (35, 'BI', 'Burundi'),
       (36, 'KH', 'Cambodia'),
       (37, 'CM', 'Cameroon'),
       (38, 'CA', 'Canada'),
       (39, 'CV', 'Cape Verde'),
       (40, 'KY', 'Cayman Islands'),
       (41, 'CF', 'Central African Republic'),
       (42, 'TD', 'Chad'),
       (43, 'CL', 'Chile'),
       (44, 'CN', 'China'),
       (45, 'CX', 'Christmas Island'),
       (46, 'CC', 'Cocos (Keeling) Islands'),
       (47, 'CO', 'Colombia'),
       (48, 'KM', 'Comoros'),
       (49, 'CG', 'Congo'),
       (50, 'CK', 'Cook Islands'),
       (51, 'CR', 'Costa Rica'),
       (52, 'HR', 'Croatia (Hrvatska)'),
       (53, 'CU', 'Cuba'),
       (54, 'CY', 'Cyprus'),
       (55, 'CZ', 'Czech Republic'),
       (56, 'DK', 'Denmark'),
       (57, 'DJ', 'Djibouti'),
       (58, 'DM', 'Dominica'),
       (59, 'DO', 'Dominican Republic'),
       (60, 'TP', 'East Timor'),
       (61, 'EC', 'Ecuador'),
       (62, 'EG', 'Egypt'),
       (63, 'SV', 'El Salvador'),
       (64, 'GQ', 'Equatorial Guinea'),
       (65, 'ER', 'Eritrea'),
       (66, 'EE', 'Estonia'),
       (67, 'ET', 'Ethiopia'),
       (68, 'FK', 'Falkland Islands (Malvinas)'),
       (69, 'FO', 'Faroe Islands'),
       (70, 'FJ', 'Fiji'),
       (71, 'FI', 'Finland'),
       (72, 'FR', 'France'),
       (73, 'FX', 'France, Metropolitan'),
       (74, 'GF', 'French Guiana'),
       (75, 'PF', 'French Polynesia'),
       (76, 'TF', 'French Southern Territories'),
       (77, 'GA', 'Gabon'),
       (78, 'GM', 'Gambia'),
       (79, 'GE', 'Georgia'),
       (80, 'DE', 'Germany'),
       (81, 'GH', 'Ghana'),
       (82, 'GI', 'Gibraltar'),
       (83, 'GK', 'Guernsey'),
       (84, 'GR', 'Greece'),
       (85, 'GL', 'Greenland'),
       (86, 'GD', 'Grenada'),
       (87, 'GP', 'Guadeloupe'),
       (88, 'GU', 'Guam'),
       (89, 'GT', 'Guatemala'),
       (90, 'GN', 'Guinea'),
       (91, 'GW', 'Guinea-Bissau'),
       (92, 'GY', 'Guyana'),
       (93, 'HT', 'Haiti'),
       (94, 'HM', 'Heard and Mc Donald Islands'),
       (95, 'HN', 'Honduras'),
       (96, 'HK', 'Hong Kong'),
       (97, 'HU', 'Hungary'),
       (98, 'IS', 'Iceland'),
       (99, 'IN', 'India'),
       (100, 'IM', 'Isle of Man'),
       (101, 'ID', 'Indonesia'),
       (102, 'IR', 'Iran (Islamic Republic of)'),
       (103, 'IQ', 'Iraq'),
       (104, 'IE', 'Ireland'),
       (105, 'IL', 'Israel'),
       (106, 'IT', 'Italy'),
       (107, 'CI', 'Ivory Coast'),
       (108, 'JE', 'Jersey'),
       (109, 'JM', 'Jamaica'),
       (110, 'JP', 'Japan'),
       (111, 'JO', 'Jordan'),
       (112, 'KZ', 'Kazakhstan'),
       (113, 'KE', 'Kenya'),
       (114, 'KI', 'Kiribati'),
       (115, 'KP', 'Korea, Democratic People''s Republic of'),
       (116, 'KR', 'Korea, Republic of'),
       (117, 'XK', 'Kosovo'),
       (118, 'KW', 'Kuwait'),
       (119, 'KG', 'Kyrgyzstan'),
       (120, 'LA', 'Lao People''s Democratic Republic'),
       (121, 'LV', 'Latvia'),
       (122, 'LB', 'Lebanon'),
       (123, 'LS', 'Lesotho'),
       (124, 'LR', 'Liberia'),
       (125, 'LY', 'Libyan Arab Jamahiriya'),
       (126, 'LI', 'Liechtenstein'),
       (127, 'LT', 'Lithuania'),
       (128, 'LU', 'Luxembourg'),
       (129, 'MO', 'Macau'),
       (130, 'MK', 'Macedonia'),
       (131, 'MG', 'Madagascar'),
       (132, 'MW', 'Malawi'),
       (133, 'MY', 'Malaysia'),
       (134, 'MV', 'Maldives'),
       (135, 'ML', 'Mali'),
       (136, 'MT', 'Malta'),
       (137, 'MH', 'Marshall Islands'),
       (138, 'MQ', 'Martinique'),
       (139, 'MR', 'Mauritania'),
       (140, 'MU', 'Mauritius'),
       (141, 'TY', 'Mayotte'),
       (142, 'MX', 'Mexico'),
       (143, 'FM', 'Micronesia, Federated States of'),
       (144, 'MD', 'Moldova, Republic of'),
       (145, 'MC', 'Monaco'),
       (146, 'MN', 'Mongolia'),
       (147, 'ME', 'Montenegro'),
       (148, 'MS', 'Montserrat'),
       (149, 'MA', 'Morocco'),
       (150, 'MZ', 'Mozambique'),
       (151, 'MM', 'Myanmar'),
       (152, 'NA', 'Namibia'),
       (153, 'NR', 'Nauru'),
       (154, 'NP', 'Nepal'),
       (155, 'NL', 'Netherlands'),
       (156, 'AN', 'Netherlands Antilles'),
       (157, 'NC', 'New Caledonia'),
       (158, 'NZ', 'New Zealand'),
       (159, 'NI', 'Nicaragua'),
       (160, 'NE', 'Niger'),
       (161, 'NG', 'Nigeria'),
       (162, 'NU', 'Niue'),
       (163, 'NF', 'Norfolk Island'),
       (164, 'MP', 'Northern Mariana Islands'),
       (165, 'NO', 'Norway'),
       (166, 'OM', 'Oman'),
       (167, 'PK', 'Pakistan'),
       (168, 'PW', 'Palau'),
       (169, 'PS', 'Palestine'),
       (170, 'PA', 'Panama'),
       (171, 'PG', 'Papua New Guinea'),
       (172, 'PY', 'Paraguay'),
       (173, 'PE', 'Peru'),
       (174, 'PH', 'Philippines'),
       (175, 'PN', 'Pitcairn'),
       (176, 'PL', 'Poland'),
       (177, 'PT', 'Portugal'),
       (178, 'PR', 'Puerto Rico'),
       (179, 'QA', 'Qatar'),
       (180, 'RE', 'Reunion'),
       (181, 'RO', 'Romania'),
       (182, 'RU', 'Russian Federation'),
       (183, 'RW', 'Rwanda'),
       (184, 'KN', 'Saint Kitts and Nevis'),
       (185, 'LC', 'Saint Lucia'),
       (186, 'VC', 'Saint Vincent and the Grenadines'),
       (187, 'WS', 'Samoa'),
       (188, 'SM', 'San Marino'),
       (189, 'ST', 'Sao Tome and Principe'),
       (190, 'SA', 'Saudi Arabia'),
       (191, 'SN', 'Senegal'),
       (192, 'RS', 'Serbia'),
       (193, 'SC', 'Seychelles'),
       (194, 'SL', 'Sierra Leone'),
       (195, 'SG', 'Singapore'),
       (196, 'SK', 'Slovakia'),
       (197, 'SI', 'Slovenia'),
       (198, 'SB', 'Solomon Islands'),
       (199, 'SO', 'Somalia'),
       (200, 'ZA', 'South Africa'),
       (201, 'GS', 'South Georgia South Sandwich Islands'),
       (202, 'ES', 'Spain'),
       (203, 'LK', 'Sri Lanka'),
       (204, 'SH', 'St. Helena'),
       (205, 'PM', 'St. Pierre and Miquelon'),
       (206, 'SD', 'Sudan'),
       (207, 'SR', 'Suriname'),
       (208, 'SJ', 'Svalbard and Jan Mayen Islands'),
       (209, 'SZ', 'Swaziland'),
       (210, 'SE', 'Sweden'),
       (211, 'CH', 'Switzerland'),
       (212, 'SY', 'Syrian Arab Republic'),
       (213, 'TW', 'Taiwan'),
       (214, 'TJ', 'Tajikistan'),
       (215, 'TZ', 'Tanzania, United Republic of'),
       (216, 'TH', 'Thailand'),
       (217, 'TG', 'Togo'),
       (218, 'TK', 'Tokelau'),
       (219, 'TO', 'Tonga'),
       (220, 'TT', 'Trinidad and Tobago'),
       (221, 'TN', 'Tunisia'),
       (222, 'TR', 'Turkey'),
       (223, 'TM', 'Turkmenistan'),
       (224, 'TC', 'Turks and Caicos Islands'),
       (225, 'TV', 'Tuvalu'),
       (226, 'UG', 'Uganda'),
       (227, 'UA', 'Ukraine'),
       (228, 'AE', 'United Arab Emirates'),
       (229, 'GB', 'United Kingdom'),
       (230, 'US', 'United States'),
       (231, 'UM', 'United States minor outlying islands'),
       (232, 'UY', 'Uruguay'),
       (233, 'UZ', 'Uzbekistan'),
       (234, 'VU', 'Vanuatu'),
       (235, 'VA', 'Vatican City State'),
       (236, 'VE', 'Venezuela'),
       (237, 'VN', 'Vietnam'),
       (238, 'VG', 'Virgin Islands (British)'),
       (239, 'VI', 'Virgin Islands (U.S.)'),
       (240, 'WF', 'Wallis and Futuna Islands'),
       (241, 'EH', 'Western Sahara'),
       (242, 'YE', 'Yemen'),
       (243, 'ZR', 'Zaire'),
       (244, 'ZM', 'Zambia'),
       (245, 'ZW', 'Zimbabwe');DROP TABLE IF EXISTS genres;

CREATE TABLE IF NOT EXISTS genres (
    id SERIAL PRIMARY KEY,
    name VARCHAR(80) NOT NULL
);

INSERT INTO genres (name)
VALUES
    ('Science fiction fandom'),
    ('Diary and Novel'),
    ('Fantasy literature'),
    ('War'),
    ('Epistolary novel'),
    ('Künstlerroman'),
    ('Short stories'),
    ('Legal thriller'),
    ('Bush poetry'),
    ('Fantasy novel'),
    ('Sketch story'),
    ('Romance novel'),
    ('Christian literature'),
    ('Autobiographical novel'),
    ('Business'),
    ('Poem'),
    ('Planetary romance'),
    ('Utopian fiction'),
    ('Romantic novel'),
    ('Young-adult fiction'),
    ('Non-fiction'),
    ('Poetry'),
    ('Historical'),
    ('unknown'),
    ('Nature writing'),
    ('Non-Fiction'),
    ('Christian fiction'),
    ('Tragicomedy'),
    ('Detective stories'),
    ('Children''s Literature'),
    ('Encyclopedia'),
    ('Thriller (genre)'),
    ('Christian novel'),
    ('Fairytale fantasy'),
    ('Satirical'),
    ('Christian Apologetics'),
    ('Crime fiction'),
    ('Prose poetry'),
    ('Young adult fiction'),
    ('Philosophy'),
    ('Humor'),
    ('Historical fantasy'),
    ('Detective fiction'),
    ('Hindi'),
    ('Biography in literature'),
    ('Decadent movement'),
    ('Cookbook'),
    ('Verse novel'),
    ('Apocalyptic and post-apocalyptic fiction'),
    ('Textbook'),
    ('Essay'),
    ('History of Ideas'),
    ('Adventure novel'),
    ('Family saga'),
    ('Mystery novel'),
    ('Short story'),
    ('Novella'),
    ('Children''s literature'),
    ('Dystopian'),
    ('Captivity narrative'),
    ('Biographical novel'),
    ('Comedy'),
    ('Science fantasy'),
    ('Detective novel'),
    ('Lost World (genre)'),
    ('Spiritual autobiography'),
    ('Short story cycle'),
    ('Social commentary'),
    ('Political journalism'),
    ('Adventure fiction'),
    ('Nonfiction'),
    ('Thriller fiction'),
    ('Picture book'),
    ('Historical mystery'),
    ('Comic novel'),
    ('Monograph'),
    ('Alternate history'),
    ('Political philosophy'),
    ('Horror novel'),
    ('Comedy novel'),
    ('Science'),
    ('Photography'),
    ('Science fiction'),
    ('Historical Fiction'),
    ('Travel literature'),
    ('Thriller novel'),
    ('Literary realism'),
    ('Historical fiction'),
    ('Philosophical novel'),
    ('Fiction'),
    ('Ruritanian romance'),
    ('Tragedy'),
    ('Dystopian novel'),
    ('Cryptozoology'),
    ('Children''s book'),
    ('Black comedy'),
    ('Cultural criticism'),
    ('Fantasy/Ethnic novel'),
    ('Crime novel'),
    ('Western fiction'),
    ('Economics'),
    ('Political'),
    ('Gothic fiction'),
    ('Satire'),
    ('Syair'),
    ('Temperance movement'),
    ('Sword and sorcery'),
    ('Wuxia'),
    ('Utopian novel'),
    ('Bildungsroman'),
    ('Fantasy'),
    ('Children''s novel'),
    ('Slave narrative'),
    ('Frame story'),
    ('Non-Profit'),
    ('Novel of manners'),
    ('Canadian literature'),
    ('Interior design'),
    ('Victorian literature'),
    ('Folklore'),
    ('Christian mythology'),
    ('Military science fiction'),
    ('Historical novels'),
    ('Chivalric romance'),
    ('Juvenile literature'),
    ('Reference work'),
    ('Young-Adult Fiction'),
    ('Drama'),
    ('Travel writing'),
    ('Political novel'),
    ('Science Fantasy'),
    ('Romanticism'),
    ('Christian mysticism'),
    ('Utopian and dystopian fiction'),
    ('Mystery (fiction)'),
    ('Western novel'),
    ('Children''s fiction'),
    ('World War II'),
    ('Theodicy'),
    ('Feminist science fiction'),
    ('Fairy tale'),
    ('Horror fiction'),
    ('Sensation novel'),
    ('Psychological novel'),
    ('Military history'),
    ('Western (genre)'),
    ('Autobiography'),
    ('War novel'),
    ('Political thriller'),
    ('Self-help'),
    ('Roman à clef'),
    ('Fantasy fiction'),
    ('Children''s books'),
    ('Historical Novel'),
    ('Biography'),
    ('Psychological Thriller'),
    ('Mystery fiction'),
    ('Young adult novel'),
    ('Historical novel'),
    ('Gaucho literature'),
    ('Contemporary romance'),
    ('Apocalyptic fiction'),
    ('Nonsense poetry'),
    ('Adventure'),
    ('Philosophical literature'),
    ('Spy novel'),
    ('History'),
    ('Philosophical fiction'),
    ('Young adult novels'),
    ('Memoir'),
    ('Dark fantasy'),
    ('Gothic novel'),
    ('Novel');
DROP TABLE IF EXISTS novels;

CREATE TABLE IF NOT EXISTS novels (
    id SERIAL PRIMARY KEY,
    title VARCHAR(150) NOT NULL UNIQUE,
    other_titles VARCHAR(250),
    description VARCHAR(2000) NOT NULL,
    chapters INT NOT NULL,
    image_key VARCHAR(100) NOT NULL,
    state_id int NOT NULL REFERENCES states(id),
    country_id int NOT NULL REFERENCES countries(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_timestamp
    BEFORE UPDATE ON novels
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();DROP TABLE IF EXISTS tomes;

CREATE TABLE IF NOT EXISTS tomes (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    novel_id INT REFERENCES novels(id)
);DROP TABLE IF EXISTS chapters;

CREATE TABLE IF NOT EXISTS chapters (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    likes INT DEFAULT 0,
    tomes_id INT REFERENCES tomes(id)
);DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    content VARCHAR(1200) NOT NULL,
    user_id int NOT NULL REFERENCES users(id),
    chapter_id int NOT NULL REFERENCES chapters(id),
    parent_comment_id int REFERENCES comments(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_timestamp
    BEFORE UPDATE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();DROP TABLE IF EXISTS ratings;

CREATE TABLE IF NOT EXISTS ratings (
     id SERIAL PRIMARY KEY,
     novel_id INT NOT NULL,
     rating INT NOT NULL,
     voter_count INT NOT NULL,
     FOREIGN KEY (novel_id) REFERENCES novels(id)
);
DROP TABLE IF EXISTS novel_genre;

CREATE TABLE IF NOT EXISTS novel_genre (
    id SERIAL PRIMARY KEY,
    novel_id INT,
    genre_id INT,
    FOREIGN KEY (novel_id) REFERENCES novels(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);DROP TABLE IF EXISTS tags;

CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(70) NOT NULL
);

INSERT INTO tags (name)
VALUES
    ('Romance'),
    ('Adventure'),
    ('Fantasy'),
    ('Science Fiction'),
    ('Mystery'),
    ('Horror'),
    ('Historical'),
    ('Thriller'),
    ('Crime'),
    ('Drama'),
    ('Comedy'),
    ('Tragedy'),
    ('Action'),
    ('Psychological'),
    ('Supernatural'),
    ('Paranormal'),
    ('Magic'),
    ('Epic'),
    ('Mythology'),
    ('Folklore'),
    ('Satire'),
    ('Political'),
    ('Military'),
    ('Apocalyptic'),
    ('Post-apocalyptic'),
    ('Dystopian'),
    ('Utopian'),
    ('Alternate History'),
    ('Time Travel'),
    ('Space Opera'),
    ('Urban Fantasy'),
    ('High Fantasy'),
    ('Sword and Sorcery'),
    ('Steampunk'),
    ('Cyberpunk'),
    ('Dark Fantasy'),
    ('Fairy Tale'),
    ('Heroic Fantasy'),
    ('Magical Realism'),
    ('Gothic'),
    ('Southern Gothic'),
    ('Noir'),
    ('Detective'),
    ('Legal'),
    ('Medical'),
    ('Spy'),
    ('Espionage'),
    ('Romantic Suspense'),
    ('Adventure Fantasy'),
    ('Bildungsroman'),
    ('Coming of Age'),
    ('Family Saga'),
    ('Historical Romance'),
    ('Contemporary Romance'),
    ('Paranormal Romance'),
    ('Historical Fiction'),
    ('Contemporary Fiction'),
    ('Literary Fiction'),
    ('Epistolary'),
    ('Satirical'),
    ('Young Adult'),
    ('Middle Grade'),
    ('Children'),
    ('Folk Tale'),
    ('Short Story'),
    ('Novella'),
    ('Serialized'),
    ('Flash Fiction'),
    ('Anthology'),
    ('Epic Poetry'),
    ('Narrative Poetry'),
    ('Lyric Poetry'),
    ('Dramatic Poetry'),
    ('Fantasy Adventure'),
    ('Historical Mystery'),
    ('Psychological Thriller'),
    ('Cozy Mystery'),
    ('Western'),
    ('Romantic Comedy'),
    ('Christian Fiction'),
    ('Spiritual'),
    ('Inspirational'),
    ('Self-Help'),
    ('Biography'),
    ('Autobiography'),
    ('Memoir'),
    ('Non-fiction'),
    ('True Crime'),
    ('Essay'),
    ('Criticism'),
    ('Philosophy'),
    ('Journalism'),
    ('Travel'),
    ('Nature'),
    ('Science'),
    ('Economics'),
    ('Politics'),
    ('Sociology'),
    ('Anthropology'),
    ('History'),
    ('Culture'),
    ('Religion'),
    ('Myth'),
    ('Fable'),
    ('Parable'),
    ('Comic'),
    ('Graphic Novel'),
    ('Webcomic'),
    ('Light Novel'),
    ('Visual Novel'),
    ('Gamebook'),
    ('Interactive Fiction'),
    ('Fan Fiction'),
    ('Erotica'),
    ('LGBTQ+ Fiction'),
    ('Queer Fiction'),
    ('Gender Studies'),
    ('Feminist Fiction'),
    ('Black Literature'),
    ('Asian Literature'),
    ('Indigenous Literature'),
    ('Magical School'),
    ('Pirate Adventure'),
    ('Vampire'),
    ('Zombie'),
    ('Werewolf'),
    ('Demon'),
    ('Angel'),
    ('Ghost'),
    ('Alien'),
    ('Robot'),
    ('Cyborg'),
    ('Artificial Intelligence'),
    ('Virtual Reality'),
    ('Cybernetic'),
    ('Biopunk'),
    ('Climate Fiction'),
    ('Cli-Fi'),
    ('Eco-Fiction'),
    ('Ecological'),
    ('Agricultural'),
    ('Urban'),
    ('Rural'),
    ('Country Life'),
    ('City Life'),
    ('Survival'),
    ('Sports'),
    ('Music'),
    ('Art'),
    ('Food'),
    ('Cooking'),
    ('Gardening'),
    ('Crafts'),
    ('Hobbies'),
    ('Education'),
    ('School'),
    ('College'),
    ('University'),
    ('Workplace'),
    ('Corporate'),
    ('Business'),
    ('Entrepreneurship'),
    ('Finance'),
    ('Technology'),
    ('Gaming'),
    ('Adventure Travel'),
    ('Exploration'),
    ('Expedition'),
    ('Voyage'),
    ('Quest'),
    ('Journey'),
    ('Road Trip'),
    ('Pilgrimage'),
    ('Expeditionary'),
    ('Survivor'),
    ('Exile'),
    ('Refugee'),
    ('Alien Invasion'),
    ('Demonic Possession'),
    ('Haunting'),
    ('Cursed Object'),
    ('Magic School'),
    ('Heist'),
    ('Conspiracy'),
    ('Secret Society'),
    ('Cult'),
    ('Ritual'),
    ('Prophecy'),
    ('Fugitive'),
    ('Outlaw'),
    ('Revenge'),
    ('Vendetta'),
    ('Crusade'),
    ('Resistance'),
    ('Revolution'),
    ('War'),
    ('Conflict'),
    ('Battle'),
    ('Siege'),
    ('Occupation'),
    ('Resistance Movement'),
    ('Spy Game'),
    ('Undercover'),
    ('Deception'),
    ('Betrayal'),
    ('Treachery'),
    ('Infiltration'),
    ('Espionage'),
    ('Counter-espionage'),
    ('Insurrection'),
    ('Insurgency'),
    ('Guerrilla'),
    ('Rebel'),
    ('Patriot'),
    ('Martyr'),
    ('Heroism'),
    ('Sacrifice'),
    ('Survivor'),
    ('Savior'),
    ('Protector'),
    ('Guardian'),
    ('Champion'),
    ('Defender'),
    ('Avenger'),
    ('Justice'),
    ('Law'),
    ('Order'),
    ('Chaos'),
    ('Anarchy'),
    ('Tyranny'),
    ('Oppression'),
    ('Liberation'),
    ('Freedom'),
    ('Civil Rights'),
    ('Equality'),
    ('Justice System'),
    ('Courtroom Drama'),
    ('Legal Thriller'),
    ('Medical Drama'),
    ('Hospital'),
    ('Doctor'),
    ('Nurse'),
    ('Patient'),
    ('Disease'),
    ('Epidemic'),
    ('Pandemic'),
    ('Outbreak'),
    ('Plague'),
    ('Infection'),
    ('Virus'),
    ('Bacteria'),
    ('Parasite'),
    ('Immunology'),
    ('Genetics'),
    ('DNA'),
    ('Genome'),
    ('Biotechnology'),
    ('Cloning'),
    ('Genetic Engineering'),
    ('Mutation'),
    ('Hybrid'),
    ('Cyborg'),
    ('Android'),
    ('Robot'),
    ('Artificial Intelligence'),
    ('Machine Learning'),
    ('Neural Network'),
    ('Quantum Computing'),
    ('Virtual Reality'),
    ('Augmented Reality'),
    ('Mixed Reality'),
    ('Simulated Reality'),
    ('Holography'),
    ('Simulation'),
    ('Digital World'),
    ('Cyber Space'),
    ('Internet'),
    ('Web'),
    ('Network'),
    ('Grid'),
    ('Cloud'),
    ('Big Data'),
    ('Data Science'),
    ('Data Mining'),
    ('Data Analysis'),
    ('Algorithm'),
    ('Program'),
    ('Software'),
    ('Application'),
    ('App'),
    ('Platform'),
    ('System'),
    ('Database'),
    ('Blockchain'),
    ('Cryptocurrency'),
    ('Bitcoin'),
    ('Ethereum'),
    ('Token'),
    ('Smart Contract'),
    ('Decentralized'),
    ('Distributed'),
    ('Peer-to-Peer'),
    ('Network Protocol'),
    ('Security'),
    ('Encryption'),
    ('Decryption'),
    ('Cryptography'),
    ('Cybersecurity'),
    ('Hacking'),
    ('Phishing'),
    ('Malware'),
    ('Virus'),
    ('Trojan'),
    ('Worm'),
    ('Ransomware'),
    ('Spyware'),
    ('Adware'),
    ('Rootkit'),
    ('Exploit'),
    ('Backdoor'),
    ('Zero-Day'),
    ('Vulnerability'),
    ('Patch'),
    ('Update'),
    ('Upgrade'),
    ('Version'),
    ('Release'),
    ('Beta'),
    ('Alpha'),
    ('Prototype'),
    ('Proof of Concept'),
    ('Minimum Viable Product'),
    ('Startup'),
    ('Entrepreneur'),
    ('Founder'),
    ('Co-founder'),
    ('CEO'),
    ('CTO'),
    ('CFO'),
    ('COO'),
    ('CMO'),
    ('CSO'),
    ('CXO'),
    ('VP'),
    ('Director'),
    ('Manager'),
    ('Team Leader'),
    ('Team Member'),
    ('Employee'),
    ('Staff'),
    ('Worker'),
    ('Laborer'),
    ('Contractor'),
    ('Freelancer'),
    ('Consultant'),
    ('Advisor'),
    ('Mentor'),
    ('Coach'),
    ('Trainer'),
    ('Instructor'),
    ('Educator'),
    ('Teacher'),
    ('Professor'),
    ('Lecturer'),
    ('Researcher'),
    ('Scientist'),
    ('Engineer'),
    ('Technician'),
    ('Technologist'),
    ('Specialist'),
    ('Expert'),
    ('Analyst'),
    ('Architect'),
    ('Designer'),
    ('Developer'),
    ('Programmer'),
    ('Coder'),
    ('Hacker'),
    ('Marketer'),
    ('Salesperson'),
    ('Businessperson'),
    ('Executive'),
    ('Administrator'),
    ('Supervisor'),
    ('Coordinator'),
    ('Planner'),
    ('Organizer'),
    ('Operator'),
    ('Agent'),
    ('Representative'),
    ('Advocate'),
    ('Activist'),
    ('Volunteer'),
    ('Campaigner'),
    ('Organizer'),
    ('Leader'),
    ('Commander'),
    ('Chief'),
    ('Captain'),
    ('Admiral'),
    ('General'),
    ('Colonel'),
    ('Major'),
    ('Lieutenant'),
    ('Sergeant'),
    ('Corporal'),
    ('Private'),
    ('Cadet'),
    ('Recruit'),
    ('Sold'),
    ('Psychological Horror'),
    ('Historical Fantasy'),
    ('Alternate Universe'),
    ('Superhero'),
    ('Mecha'),
    ('Wuxia'),
    ('Xianxia'),
    ('Space Western'),
    ('Dark Comedy'),
    ('Eco-Thriller'),
    ('Political Thriller'),
    ('Urban Legend'),
    ('Gothic Romance'),
    ('Mythic Fantasy'),
    ('Supernatural Thriller'),
    ('Legal Mystery'),
    ('Medical Thriller'),
    ('Crime Comedy'),
    ('Road Novel'),
    ('Black Comedy'),
    ('Workplace Comedy'),
    ('Campus Novel'),
    ('Cli-Fi Romance'),
    ('Biopunk Thriller'),
    ('Arctic Adventure'),
    ('Desert Fantasy'),
    ('Oceanic Adventure'),
    ('Courtroom Drama'),
    ('Psychological Drama'),
    ('Historical Drama'),
    ('Military Science Fiction'),
    ('Fantasy of Manners'),
    ('Allegory'),
    ('Cyberpunk Romance'),
    ('Historical Epic'),
    ('Urban Myth'),
    ('Epic Fantasy'),
    ('Low Fantasy'),
    ('Animal Fantasy'),
    ('Portal Fantasy'),
    ('Heroic Legend'),
    ('Mythic Romance'),
    ('Speculative Fiction'),
    ('Postcolonial Fiction'),
    ('Metafiction'),
    ('Urban Horror'),
    ('Psychoanalytic Fiction'),
    ('Nautical Fiction'),
    ('Historical Adventure'),
    ('Science Fantasy'),
    ('Mythic Adventure'),
    ('Fantasy Mystery'),
    ('Post-apocalyptic Thriller'),
    ('Romantic Fantasy'),
    ('Science Fiction Romance'),
    ('Alternate History Mystery'),
    ('Dark Romance'),
    ('Urban Adventure'),
    ('Supernatural Romance'),
    ('Romantic Adventure'),
    ('Psychological Horror Thriller'),
    ('High Fantasy Romance'),
    ('Military Thriller'),
    ('Mystery Thriller'),
    ('Epic Mystery'),
    ('Technothriller'),
    ('Fantasy of Manners Romance'),
    ('Superhero Comedy'),
    ('Superhero Romance'),
    ('Post-apocalyptic Romance'),
    ('Urban Fantasy Romance'),
    ('Sword and Sorcery Adventure'),
    ('Time Travel Romance'),
    ('Science Fiction Adventure'),
    ('Gothic Horror'),
    ('Epic Historical Romance'),
    ('Urban Fantasy Mystery'),
    ('Science Fantasy Adventure'),
    ('Noir Mystery'),
    ('Historical Gothic'),
    ('Magical Realism Mystery'),
    ('Psychological Fantasy'),
    ('Dystopian Thriller'),
    ('Alternate History Fantasy'),
    ('Political Satire'),
    ('Magical Realism Romance'),
    ('Ecological Thriller'),
    ('Zombie Apocalypse'),
    ('Space Fantasy'),
    ('Fantasy Adventure Romance'),
    ('Historical Fantasy Romance'),
    ('Adventure Mystery'),
    ('Time Travel Mystery'),
    ('Post-apocalyptic Fantasy'),
    ('Urban Science Fiction'),
    ('Supernatural Adventure'),
    ('Space Adventure'),
    ('Horror Mystery'),
    ('Supernatural Fantasy'),
    ('Mythic Mystery'),
    ('Gothic Mystery'),
    ('Romantic Mystery'),
    ('Mythical Romance'),
    ('Steampunk Adventure'),
    ('Urban Fantasy Adventure'),
    ('Paranormal Fantasy'),
    ('Science Fiction Mystery'),
    ('Science Fiction Comedy'),
    ('Urban Fantasy Horror'),
    ('Alternate History Adventure'),
    ('Post-apocalyptic Science Fiction'),
    ('Space Opera Romance'),
    ('Science Fantasy Romance'),
    ('Magical Adventure'),
    ('Dark Fantasy Romance'),
    ('High Fantasy Adventure'),
    ('Speculative Adventure'),
    ('Heroic Fantasy Adventure'),
    ('Political Fantasy'),
    ('Urban Fantasy Thriller'),
    ('Supernatural Mystery'),
    ('Science Fiction Thriller'),
    ('Dystopian Science Fiction'),
    ('Gothic Adventure'),
    ('Fantasy Thriller'),
    ('Steampunk Fantasy'),
    ('Urban Fantasy Thriller'),
    ('Alternate History Romance'),
    ('Speculative Romance'),
    ('Heroic Fantasy Romance'),
    ('Epic Science Fiction'),
    ('Mythic Science Fiction'),
    ('Fantasy of Manners Mystery'),
    ('Steampunk Mystery'),
    ('Cyberpunk Thriller'),
    ('Psychological Science Fiction'),
    ('Supernatural Horror'),
    ('Post-apocalyptic Horror'),
    ('Gothic Thriller'),
    ('Technological Thriller'),
    ('Psychological Thriller Romance'),
    ('Medical Mystery'),
    ('Military Adventure'),
    ('Historical Thriller'),
    ('Romantic Mystery Thriller'),
    ('Science Fiction Fantasy'),
    ('Urban Fantasy Mystery Romance'),
    ('Political Mystery'),
    ('Eco-Thriller Romance');
DROP TABLE IF EXISTS novel_tags;

-- TODO: refactor table name
CREATE TABLE IF NOT EXISTS novel_tags (
    id SERIAL PRIMARY KEY,
    novel_id INT,
    tag_id INT,
    FOREIGN KEY (novel_id) REFERENCES novels(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);