DROP TABLE IF EXISTS genres;

CREATE TABLE IF NOT EXISTS genres (
    id SERIAL PRIMARY KEY,
    name VARCHAR(80) NOT NULL
);

INSERT INTO genres (name)
VALUES
    ('Science fiction fandom'),
    ('Diary and Novel'),
    ('Fantasy literature'),
    ('War'),
    ('Epistolary novel'),
    ('Künstlerroman'),
    ('Short stories'),
    ('Legal thriller'),
    ('Bush poetry'),
    ('Fantasy novel'),
    ('Sketch story'),
    ('Romance novel'),
    ('Christian literature'),
    ('Autobiographical novel'),
    ('Business'),
    ('Poem'),
    ('Planetary romance'),
    ('Utopian fiction'),
    ('Romantic novel'),
    ('Young-adult fiction'),
    ('Non-fiction'),
    ('Poetry'),
    ('Historical'),
    ('unknown'),
    ('Nature writing'),
    ('Non-Fiction'),
    ('Christian fiction'),
    ('Tragicomedy'),
    ('Detective stories'),
    ('Children''s Literature'),
    ('Encyclopedia'),
    ('Thriller (genre)'),
    ('Christian novel'),
    ('Fairytale fantasy'),
    ('Satirical'),
    ('Christian Apologetics'),
    ('Crime fiction'),
    ('Prose poetry'),
    ('Young adult fiction'),
    ('Philosophy'),
    ('Humor'),
    ('Historical fantasy'),
    ('Detective fiction'),
    ('Hindi'),
    ('Biography in literature'),
    ('Decadent movement'),
    ('Cookbook'),
    ('Verse novel'),
    ('Apocalyptic and post-apocalyptic fiction'),
    ('Textbook'),
    ('Essay'),
    ('History of Ideas'),
    ('Adventure novel'),
    ('Family saga'),
    ('Mystery novel'),
    ('Short story'),
    ('Novella'),
    ('Children''s literature'),
    ('Dystopian'),
    ('Captivity narrative'),
    ('Biographical novel'),
    ('Comedy'),
    ('Science fantasy'),
    ('Detective novel'),
    ('Lost World (genre)'),
    ('Spiritual autobiography'),
    ('Short story cycle'),
    ('Social commentary'),
    ('Political journalism'),
    ('Adventure fiction'),
    ('Nonfiction'),
    ('Thriller fiction'),
    ('Picture book'),
    ('Historical mystery'),
    ('Comic novel'),
    ('Monograph'),
    ('Alternate history'),
    ('Political philosophy'),
    ('Horror novel'),
    ('Comedy novel'),
    ('Science'),
    ('Photography'),
    ('Science fiction'),
    ('Historical Fiction'),
    ('Travel literature'),
    ('Thriller novel'),
    ('Literary realism'),
    ('Historical fiction'),
    ('Philosophical novel'),
    ('Fiction'),
    ('Ruritanian romance'),
    ('Tragedy'),
    ('Dystopian novel'),
    ('Cryptozoology'),
    ('Children''s book'),
    ('Black comedy'),
    ('Cultural criticism'),
    ('Fantasy/Ethnic novel'),
    ('Crime novel'),
    ('Western fiction'),
    ('Economics'),
    ('Political'),
    ('Gothic fiction'),
    ('Satire'),
    ('Syair'),
    ('Temperance movement'),
    ('Sword and sorcery'),
    ('Wuxia'),
    ('Utopian novel'),
    ('Bildungsroman'),
    ('Fantasy'),
    ('Children''s novel'),
    ('Slave narrative'),
    ('Frame story'),
    ('Non-Profit'),
    ('Novel of manners'),
    ('Canadian literature'),
    ('Interior design'),
    ('Victorian literature'),
    ('Folklore'),
    ('Christian mythology'),
    ('Military science fiction'),
    ('Historical novels'),
    ('Chivalric romance'),
    ('Juvenile literature'),
    ('Reference work'),
    ('Young-Adult Fiction'),
    ('Drama'),
    ('Travel writing'),
    ('Political novel'),
    ('Science Fantasy'),
    ('Romanticism'),
    ('Christian mysticism'),
    ('Utopian and dystopian fiction'),
    ('Mystery (fiction)'),
    ('Western novel'),
    ('Children''s fiction'),
    ('World War II'),
    ('Theodicy'),
    ('Feminist science fiction'),
    ('Fairy tale'),
    ('Horror fiction'),
    ('Sensation novel'),
    ('Psychological novel'),
    ('Military history'),
    ('Western (genre)'),
    ('Autobiography'),
    ('War novel'),
    ('Political thriller'),
    ('Self-help'),
    ('Roman à clef'),
    ('Fantasy fiction'),
    ('Children''s books'),
    ('Historical Novel'),
    ('Biography'),
    ('Psychological Thriller'),
    ('Mystery fiction'),
    ('Young adult novel'),
    ('Historical novel'),
    ('Gaucho literature'),
    ('Contemporary romance'),
    ('Apocalyptic fiction'),
    ('Nonsense poetry'),
    ('Adventure'),
    ('Philosophical literature'),
    ('Spy novel'),
    ('History'),
    ('Philosophical fiction'),
    ('Young adult novels'),
    ('Memoir'),
    ('Dark fantasy'),
    ('Gothic novel'),
    ('Novel');
