DROP TABLE IF EXISTS tags;

CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(70) NOT NULL
);

INSERT INTO tags (name)
VALUES
    ('Romance'),
    ('Adventure'),
    ('Fantasy'),
    ('Science Fiction'),
    ('Mystery'),
    ('Horror'),
    ('Historical'),
    ('Thriller'),
    ('Crime'),
    ('Drama'),
    ('Comedy'),
    ('Tragedy'),
    ('Action'),
    ('Psychological'),
    ('Supernatural'),
    ('Paranormal'),
    ('Magic'),
    ('Epic'),
    ('Mythology'),
    ('Folklore'),
    ('Satire'),
    ('Political'),
    ('Military'),
    ('Apocalyptic'),
    ('Post-apocalyptic'),
    ('Dystopian'),
    ('Utopian'),
    ('Alternate History'),
    ('Time Travel'),
    ('Space Opera'),
    ('Urban Fantasy'),
    ('High Fantasy'),
    ('Sword and Sorcery'),
    ('Steampunk'),
    ('Cyberpunk'),
    ('Dark Fantasy'),
    ('Fairy Tale'),
    ('Heroic Fantasy'),
    ('Magical Realism'),
    ('Gothic'),
    ('Southern Gothic'),
    ('Noir'),
    ('Detective'),
    ('Legal'),
    ('Medical'),
    ('Spy'),
    ('Espionage'),
    ('Romantic Suspense'),
    ('Adventure Fantasy'),
    ('Bildungsroman'),
    ('Coming of Age'),
    ('Family Saga'),
    ('Historical Romance'),
    ('Contemporary Romance'),
    ('Paranormal Romance'),
    ('Historical Fiction'),
    ('Contemporary Fiction'),
    ('Literary Fiction'),
    ('Epistolary'),
    ('Satirical'),
    ('Young Adult'),
    ('Middle Grade'),
    ('Children'),
    ('Folk Tale'),
    ('Short Story'),
    ('Novella'),
    ('Serialized'),
    ('Flash Fiction'),
    ('Anthology'),
    ('Epic Poetry'),
    ('Narrative Poetry'),
    ('Lyric Poetry'),
    ('Dramatic Poetry'),
    ('Fantasy Adventure'),
    ('Historical Mystery'),
    ('Psychological Thriller'),
    ('Cozy Mystery'),
    ('Western'),
    ('Romantic Comedy'),
    ('Christian Fiction'),
    ('Spiritual'),
    ('Inspirational'),
    ('Self-Help'),
    ('Biography'),
    ('Autobiography'),
    ('Memoir'),
    ('Non-fiction'),
    ('True Crime'),
    ('Essay'),
    ('Criticism'),
    ('Philosophy'),
    ('Journalism'),
    ('Travel'),
    ('Nature'),
    ('Science'),
    ('Economics'),
    ('Politics'),
    ('Sociology'),
    ('Anthropology'),
    ('History'),
    ('Culture'),
    ('Religion'),
    ('Myth'),
    ('Fable'),
    ('Parable'),
    ('Comic'),
    ('Graphic Novel'),
    ('Webcomic'),
    ('Light Novel'),
    ('Visual Novel'),
    ('Gamebook'),
    ('Interactive Fiction'),
    ('Fan Fiction'),
    ('Erotica'),
    ('LGBTQ+ Fiction'),
    ('Queer Fiction'),
    ('Gender Studies'),
    ('Feminist Fiction'),
    ('Black Literature'),
    ('Asian Literature'),
    ('Indigenous Literature'),
    ('Magical School'),
    ('Pirate Adventure'),
    ('Vampire'),
    ('Zombie'),
    ('Werewolf'),
    ('Demon'),
    ('Angel'),
    ('Ghost'),
    ('Alien'),
    ('Robot'),
    ('Cyborg'),
    ('Artificial Intelligence'),
    ('Virtual Reality'),
    ('Cybernetic'),
    ('Biopunk'),
    ('Climate Fiction'),
    ('Cli-Fi'),
    ('Eco-Fiction'),
    ('Ecological'),
    ('Agricultural'),
    ('Urban'),
    ('Rural'),
    ('Country Life'),
    ('City Life'),
    ('Survival'),
    ('Sports'),
    ('Music'),
    ('Art'),
    ('Food'),
    ('Cooking'),
    ('Gardening'),
    ('Crafts'),
    ('Hobbies'),
    ('Education'),
    ('School'),
    ('College'),
    ('University'),
    ('Workplace'),
    ('Corporate'),
    ('Business'),
    ('Entrepreneurship'),
    ('Finance'),
    ('Technology'),
    ('Gaming'),
    ('Adventure Travel'),
    ('Exploration'),
    ('Expedition'),
    ('Voyage'),
    ('Quest'),
    ('Journey'),
    ('Road Trip'),
    ('Pilgrimage'),
    ('Expeditionary'),
    ('Survivor'),
    ('Exile'),
    ('Refugee'),
    ('Alien Invasion'),
    ('Demonic Possession'),
    ('Haunting'),
    ('Cursed Object'),
    ('Magic School'),
    ('Heist'),
    ('Conspiracy'),
    ('Secret Society'),
    ('Cult'),
    ('Ritual'),
    ('Prophecy'),
    ('Fugitive'),
    ('Outlaw'),
    ('Revenge'),
    ('Vendetta'),
    ('Crusade'),
    ('Resistance'),
    ('Revolution'),
    ('War'),
    ('Conflict'),
    ('Battle'),
    ('Siege'),
    ('Occupation'),
    ('Resistance Movement'),
    ('Spy Game'),
    ('Undercover'),
    ('Deception'),
    ('Betrayal'),
    ('Treachery'),
    ('Infiltration'),
    ('Espionage'),
    ('Counter-espionage'),
    ('Insurrection'),
    ('Insurgency'),
    ('Guerrilla'),
    ('Rebel'),
    ('Patriot'),
    ('Martyr'),
    ('Heroism'),
    ('Sacrifice'),
    ('Survivor'),
    ('Savior'),
    ('Protector'),
    ('Guardian'),
    ('Champion'),
    ('Defender'),
    ('Avenger'),
    ('Justice'),
    ('Law'),
    ('Order'),
    ('Chaos'),
    ('Anarchy'),
    ('Tyranny'),
    ('Oppression'),
    ('Liberation'),
    ('Freedom'),
    ('Civil Rights'),
    ('Equality'),
    ('Justice System'),
    ('Courtroom Drama'),
    ('Legal Thriller'),
    ('Medical Drama'),
    ('Hospital'),
    ('Doctor'),
    ('Nurse'),
    ('Patient'),
    ('Disease'),
    ('Epidemic'),
    ('Pandemic'),
    ('Outbreak'),
    ('Plague'),
    ('Infection'),
    ('Virus'),
    ('Bacteria'),
    ('Parasite'),
    ('Immunology'),
    ('Genetics'),
    ('DNA'),
    ('Genome'),
    ('Biotechnology'),
    ('Cloning'),
    ('Genetic Engineering'),
    ('Mutation'),
    ('Hybrid'),
    ('Cyborg'),
    ('Android'),
    ('Robot'),
    ('Artificial Intelligence'),
    ('Machine Learning'),
    ('Neural Network'),
    ('Quantum Computing'),
    ('Virtual Reality'),
    ('Augmented Reality'),
    ('Mixed Reality'),
    ('Simulated Reality'),
    ('Holography'),
    ('Simulation'),
    ('Digital World'),
    ('Cyber Space'),
    ('Internet'),
    ('Web'),
    ('Network'),
    ('Grid'),
    ('Cloud'),
    ('Big Data'),
    ('Data Science'),
    ('Data Mining'),
    ('Data Analysis'),
    ('Algorithm'),
    ('Program'),
    ('Software'),
    ('Application'),
    ('App'),
    ('Platform'),
    ('System'),
    ('Database'),
    ('Blockchain'),
    ('Cryptocurrency'),
    ('Bitcoin'),
    ('Ethereum'),
    ('Token'),
    ('Smart Contract'),
    ('Decentralized'),
    ('Distributed'),
    ('Peer-to-Peer'),
    ('Network Protocol'),
    ('Security'),
    ('Encryption'),
    ('Decryption'),
    ('Cryptography'),
    ('Cybersecurity'),
    ('Hacking'),
    ('Phishing'),
    ('Malware'),
    ('Virus'),
    ('Trojan'),
    ('Worm'),
    ('Ransomware'),
    ('Spyware'),
    ('Adware'),
    ('Rootkit'),
    ('Exploit'),
    ('Backdoor'),
    ('Zero-Day'),
    ('Vulnerability'),
    ('Patch'),
    ('Update'),
    ('Upgrade'),
    ('Version'),
    ('Release'),
    ('Beta'),
    ('Alpha'),
    ('Prototype'),
    ('Proof of Concept'),
    ('Minimum Viable Product'),
    ('Startup'),
    ('Entrepreneur'),
    ('Founder'),
    ('Co-founder'),
    ('CEO'),
    ('CTO'),
    ('CFO'),
    ('COO'),
    ('CMO'),
    ('CSO'),
    ('CXO'),
    ('VP'),
    ('Director'),
    ('Manager'),
    ('Team Leader'),
    ('Team Member'),
    ('Employee'),
    ('Staff'),
    ('Worker'),
    ('Laborer'),
    ('Contractor'),
    ('Freelancer'),
    ('Consultant'),
    ('Advisor'),
    ('Mentor'),
    ('Coach'),
    ('Trainer'),
    ('Instructor'),
    ('Educator'),
    ('Teacher'),
    ('Professor'),
    ('Lecturer'),
    ('Researcher'),
    ('Scientist'),
    ('Engineer'),
    ('Technician'),
    ('Technologist'),
    ('Specialist'),
    ('Expert'),
    ('Analyst'),
    ('Architect'),
    ('Designer'),
    ('Developer'),
    ('Programmer'),
    ('Coder'),
    ('Hacker'),
    ('Marketer'),
    ('Salesperson'),
    ('Businessperson'),
    ('Executive'),
    ('Administrator'),
    ('Supervisor'),
    ('Coordinator'),
    ('Planner'),
    ('Organizer'),
    ('Operator'),
    ('Agent'),
    ('Representative'),
    ('Advocate'),
    ('Activist'),
    ('Volunteer'),
    ('Campaigner'),
    ('Organizer'),
    ('Leader'),
    ('Commander'),
    ('Chief'),
    ('Captain'),
    ('Admiral'),
    ('General'),
    ('Colonel'),
    ('Major'),
    ('Lieutenant'),
    ('Sergeant'),
    ('Corporal'),
    ('Private'),
    ('Cadet'),
    ('Recruit'),
    ('Sold'),
    ('Psychological Horror'),
    ('Historical Fantasy'),
    ('Alternate Universe'),
    ('Superhero'),
    ('Mecha'),
    ('Wuxia'),
    ('Xianxia'),
    ('Space Western'),
    ('Dark Comedy'),
    ('Eco-Thriller'),
    ('Political Thriller'),
    ('Urban Legend'),
    ('Gothic Romance'),
    ('Mythic Fantasy'),
    ('Supernatural Thriller'),
    ('Legal Mystery'),
    ('Medical Thriller'),
    ('Crime Comedy'),
    ('Road Novel'),
    ('Black Comedy'),
    ('Workplace Comedy'),
    ('Campus Novel'),
    ('Cli-Fi Romance'),
    ('Biopunk Thriller'),
    ('Arctic Adventure'),
    ('Desert Fantasy'),
    ('Oceanic Adventure'),
    ('Courtroom Drama'),
    ('Psychological Drama'),
    ('Historical Drama'),
    ('Military Science Fiction'),
    ('Fantasy of Manners'),
    ('Allegory'),
    ('Cyberpunk Romance'),
    ('Historical Epic'),
    ('Urban Myth'),
    ('Epic Fantasy'),
    ('Low Fantasy'),
    ('Animal Fantasy'),
    ('Portal Fantasy'),
    ('Heroic Legend'),
    ('Mythic Romance'),
    ('Speculative Fiction'),
    ('Postcolonial Fiction'),
    ('Metafiction'),
    ('Urban Horror'),
    ('Psychoanalytic Fiction'),
    ('Nautical Fiction'),
    ('Historical Adventure'),
    ('Science Fantasy'),
    ('Mythic Adventure'),
    ('Fantasy Mystery'),
    ('Post-apocalyptic Thriller'),
    ('Romantic Fantasy'),
    ('Science Fiction Romance'),
    ('Alternate History Mystery'),
    ('Dark Romance'),
    ('Urban Adventure'),
    ('Supernatural Romance'),
    ('Romantic Adventure'),
    ('Psychological Horror Thriller'),
    ('High Fantasy Romance'),
    ('Military Thriller'),
    ('Mystery Thriller'),
    ('Epic Mystery'),
    ('Technothriller'),
    ('Fantasy of Manners Romance'),
    ('Superhero Comedy'),
    ('Superhero Romance'),
    ('Post-apocalyptic Romance'),
    ('Urban Fantasy Romance'),
    ('Sword and Sorcery Adventure'),
    ('Time Travel Romance'),
    ('Science Fiction Adventure'),
    ('Gothic Horror'),
    ('Epic Historical Romance'),
    ('Urban Fantasy Mystery'),
    ('Science Fantasy Adventure'),
    ('Noir Mystery'),
    ('Historical Gothic'),
    ('Magical Realism Mystery'),
    ('Psychological Fantasy'),
    ('Dystopian Thriller'),
    ('Alternate History Fantasy'),
    ('Political Satire'),
    ('Magical Realism Romance'),
    ('Ecological Thriller'),
    ('Zombie Apocalypse'),
    ('Space Fantasy'),
    ('Fantasy Adventure Romance'),
    ('Historical Fantasy Romance'),
    ('Adventure Mystery'),
    ('Time Travel Mystery'),
    ('Post-apocalyptic Fantasy'),
    ('Urban Science Fiction'),
    ('Supernatural Adventure'),
    ('Space Adventure'),
    ('Horror Mystery'),
    ('Supernatural Fantasy'),
    ('Mythic Mystery'),
    ('Gothic Mystery'),
    ('Romantic Mystery'),
    ('Mythical Romance'),
    ('Steampunk Adventure'),
    ('Urban Fantasy Adventure'),
    ('Paranormal Fantasy'),
    ('Science Fiction Mystery'),
    ('Science Fiction Comedy'),
    ('Urban Fantasy Horror'),
    ('Alternate History Adventure'),
    ('Post-apocalyptic Science Fiction'),
    ('Space Opera Romance'),
    ('Science Fantasy Romance'),
    ('Magical Adventure'),
    ('Dark Fantasy Romance'),
    ('High Fantasy Adventure'),
    ('Speculative Adventure'),
    ('Heroic Fantasy Adventure'),
    ('Political Fantasy'),
    ('Urban Fantasy Thriller'),
    ('Supernatural Mystery'),
    ('Science Fiction Thriller'),
    ('Dystopian Science Fiction'),
    ('Gothic Adventure'),
    ('Fantasy Thriller'),
    ('Steampunk Fantasy'),
    ('Urban Fantasy Thriller'),
    ('Alternate History Romance'),
    ('Speculative Romance'),
    ('Heroic Fantasy Romance'),
    ('Epic Science Fiction'),
    ('Mythic Science Fiction'),
    ('Fantasy of Manners Mystery'),
    ('Steampunk Mystery'),
    ('Cyberpunk Thriller'),
    ('Psychological Science Fiction'),
    ('Supernatural Horror'),
    ('Post-apocalyptic Horror'),
    ('Gothic Thriller'),
    ('Technological Thriller'),
    ('Psychological Thriller Romance'),
    ('Medical Mystery'),
    ('Military Adventure'),
    ('Historical Thriller'),
    ('Romantic Mystery Thriller'),
    ('Science Fiction Fantasy'),
    ('Urban Fantasy Mystery Romance'),
    ('Political Mystery'),
    ('Eco-Thriller Romance');
